title: Kilimandscharo
description: Auf den Kilimandscharo für einen guten Zweck

url: http://5895m.de
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 3

navigation:
  - title: Startseite
    url: /index.html
  - title: Blog
    url: /articles
  - title: Spenden
    url: /spenden
  - title: Mehr
    url: /about
  - title: Kontakt
    url: /contact

social:
  # github: brianmaierjr
  # twitter: brianmaierjr
  # facebook: brianmaierjr
  email: kili@emilrugenstein.com
  # linkedin: brianmaierjr

# google_analytics: "UA-58263416-1"

disqus:
    shortname: emilrugenstein
