title: Kilimandscharo
description: Auf den Kilimandscharo für einen guten Zweck

url: https://emilrugenstein.github.io
baseurl: /kili
paginate_path: "{{ site.baseurl }}/blog/page:num/"
permalink: "{{ site.baseurl }}/blog/:title/"

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 3

navigation:
  - title: Startseite
    url: "{{ site.baseurl }}/"
  - title: Blog
    url: "{{ site.baseurl }}/blog-posts"
  - title: Spenden
    url: "{{ site.baseurl }}/spenden"
  - title: Mehr
    url: "{{ site.baseurl }}/blog/verrueckte-idee/"
  - title: Kontakt
    url: "{{ site.baseurl }}/contact"

social:
  # github: brianmaierjr
  # twitter: brianmaierjr
  # facebook: brianmaierjr
  email: kili@emilrugenstein.com
  # linkedin: brianmaierjr

# google_analytics: "UA-58263416-1"

disqus:
    shortname: 5895m-de
