title: Kilimandscharo
description: Auf den Kilimandscharo für einen guten Zweck

url: https://emilrugenstein.github.io
baseurl: /kili
paginate_path: "kili/blog/page:num/"
permalink: "kili/blog/:title/"

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 3

navigation:
  - title: Startseite
    url: "kili/"
  - title: Blog
    url: "kili/blog-posts"
  - title: Spenden
    url: "kili/spenden"
  - title: Mehr
    url: "kili/blog/verrueckte-idee/"
  - title: Kontakt
    url: "kili/contact"

social:
  # github: brianmaierjr
  # twitter: brianmaierjr
  # facebook: brianmaierjr
  email: kili@emilrugenstein.com
  # linkedin: brianmaierjr

# google_analytics: "UA-58263416-1"

disqus:
    shortname: 5895m-de
